#!/usr/bin/env python3
"""Generate OpenROAD PSM voltage-source (.loc) files for the IR-drop step.

LibreLane's OpenROAD.IRDropReport step reads ``VSRC_LOC_FILES`` (a map of
power/ground net -> .loc file). When it is unset, OpenROAD treats *every* pad on
the net as an ideal supply source, which is optimistic for a chip that also
delivers power outward to stacked top chips. This script emits .loc files that
list only the true supply-INPUT dvdd/dvss pads and deliberately omits the pads
that feed the top chips (they are current sinks, not sources).

Part 2 (modelling the current those output pads draw for the top chips) is left
for when the top-chip flows exist -- see the repo notes.

PSM .loc format (comma-separated, one source per line):
    x_um, y_um, c4_edge_length_um, voltage

x/y are the source centre in microns; the 3rd column is the C4 bump edge length
(sets the RDL search region used to attach the source to the grid); the 4th is
the source voltage. Ref: OpenROAD src/psm/doc/Vsrc_description.md.

Usage:
    gen_vsrc_loc.py --def <padring.def> --outdir librelane/pdn \
        --vdd-voltage 5.0 --exclude 2,3,6,9,10,13
"""
import argparse
import glob
import os
import re
import sys

# dvdd_pads\[<idx>\].pad <cell> + FIXED ( <x> <y> ) <orient> ;
PAD_RE = re.compile(
    r"-\s*(dvdd|dvss)_pads\\?\[(\d+)\\?\]\.pad\s+\S+\s+\+\s+\w+\s+\(\s*"
    r"(-?\d+)\s+(-?\d+)\s*\)"
)
UNITS_RE = re.compile(r"UNITS\s+DISTANCE\s+MICRONS\s+(\d+)")


def newest_padring_def(runs_dir):
    pats = glob.glob(os.path.join(runs_dir, "*", "*padring*", "*.def"))
    if not pats:
        return None
    return max(pats, key=os.path.getmtime)


def parse_pads(def_path):
    with open(def_path) as fh:
        text = fh.read()
    m = UNITS_RE.search(text)
    if not m:
        sys.exit(f"error: no 'UNITS DISTANCE MICRONS' line in {def_path}")
    units = int(m.group(1))
    pads = {"dvdd": {}, "dvss": {}}
    for kind, idx, x, y in PAD_RE.findall(text):
        pads[kind][int(idx)] = (int(x) / units, int(y) / units)
    if not pads["dvdd"] or not pads["dvss"]:
        sys.exit(f"error: found no dvdd/dvss pad placements in {def_path}")
    return pads


def write_loc(path, pads, exclude, edge, voltage, net_label):
    kept = sorted(i for i in pads if i not in exclude)
    dropped = sorted(i for i in pads if i in exclude)
    with open(path, "w") as fh:
        fh.write(f"# {net_label} voltage sources for OpenROAD PSM IR-drop.\n")
        fh.write("# Auto-generated by scripts/gen_vsrc_loc.py -- do not hand-edit.\n")
        fh.write(f"# Columns: x_um, y_um, c4_edge_length_um, voltage\n")
        fh.write(f"# Excluded (feed top chips, modelled in Part 2): {dropped}\n")
        for i in kept:
            x, y = pads[i]
            fh.write(f"{x:.3f},{y:.3f},{edge:.1f},{voltage}\n")
    return kept, dropped


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--def", dest="def_path", help="padring DEF (default: newest in runs/)")
    ap.add_argument("--runs", default=None, help="runs dir to search for newest padring DEF")
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--vdd-voltage", type=float, default=5.0)
    ap.add_argument("--exclude", default="2,3,6,9,10,13",
                    help="comma-separated dvdd_pads[]/dvss_pads[] indices that feed top chips")
    ap.add_argument("--edge", type=float, default=75.0,
                    help="C4 edge length in um (source attach region)")
    args = ap.parse_args()

    def_path = args.def_path
    if not def_path:
        runs = args.runs or os.path.join(os.path.dirname(args.outdir) or ".", "runs")
        def_path = newest_padring_def(runs)
        if not def_path:
            sys.exit(f"error: no padring DEF found under {runs}; pass --def")
    exclude = {int(x) for x in args.exclude.split(",") if x.strip() != ""}

    pads = parse_pads(def_path)
    os.makedirs(args.outdir, exist_ok=True)
    print(f"padring DEF: {def_path}")
    for net, kind, volt in (("VDD", "dvdd", args.vdd_voltage), ("VSS", "dvss", 0.0)):
        out = os.path.join(args.outdir, f"vsrc_{kind}.loc")
        kept, dropped = write_loc(out, pads[kind], exclude, args.edge, volt, net)
        print(f"  {net}: wrote {out}  sources={kept}  excluded={dropped}")


if __name__ == "__main__":
    main()
